version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
      - python
      - mysql
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot

  php:
    build: ./PHP
    volumes:
      - ./PHP:/var/www/html
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      USER: ${USER}
      MYSQL_PWD: ${MYSQL_PWD}
      MYSQL_HOST: ${MYSQL_HOST}
      
    volumes:
      - mysql-data:/var/lib/mysql

  python:
    build: ./Python
    volumes:
      - ./Python:/app
    environment:
      - DATABASE_HOST=${MYSQL_HOST}
      - DATABASE_USER=${USER}
      - DATABASE_PASSWORD=${MYSQL_PWD}
      - DATABASE_NAME=${MYSQL_DATABASE}
      - TABLE1_NAME=${TABLE1}
      - TABLE2_NAME=${TABLE2}
    depends_on:
      - mysql
    command: sh -c "sleep 10 && python build_databases.py"
  

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  mysql-data:
  certbot-etc:
  certbot-var: